### ISSUE TITLE
Issue with Contao 4.10

### ISSUE THREAD

**Issue by LupusVII** [heimrichhannot/contao-backend-lost-password-bundle#3]
Hi !
I found an issue with this package and the latest update of Contao

` Cannot autowire service "HeimrichHannot\BackendLostPasswordBundle\Control  
  le                                                                           
    r\BackendController": argument "$mailer" of method "__construct()" has ty  
  pe                                                                           
     "Swift_Mailer" but this class was not found.`

It seems it's due to this commit : #1829 Replace symfony/swiftmailer-bundle with symfony/mailer (fritzmg)

Thanks for your work!

**Comment by koertho** [comment]
@Defcon0 I think we have only two options: require swiftmailer in composer.json (`"symfony/swiftmailer-bundle": "^2.6.2 || ^3.1.5",
`) or use the legacy email class :/

**Comment by Defcon0** [comment]
OK, I changed the swiftmailer usage to contao's email class since it's the safe way for updates.

**Comment by LupusVII** [comment]
Perfect, thank you! Hope Contao will keep this Email class to make sure of the bundles compatibility :)
