### ISSUE TITLE
Didn't work in 4.9

### ISSUE THREAD

**Issue by xstable** [heimrichhannot/contao-backend-lost-password-bundle#4]
This Plugin didn't work in 4.9.

I've did the Install-Steps you noticed, but if I press the "forgot password" button, the url only switch from:
`https://xxx.de/contao/login`
to: 
`https://xxx.de/contao/login?_hash=nsnNTAIfvG27ubZzq%2FXr1o1WyOhbk%2FkipLxXsHc2G3M%3D&redirect=https%3A%2F%2Fxxx.de%2Fcontao-be-lost-password%2Fpassword%2Frequest`

And the default login-page is shown again... thats it... nothing else happend.

**Comment by Defcon0** [comment]
OK, I added a fix for contao 4.9. It should work now (in my local environment it did ;-) ). Although I didn't have the behavior you're experiencing. It seems your system "think" the url is backend login protected which it isnÄ't according to:

https://github.com/heimrichhannot/contao-backend-lost-password-bundle/blob/ea498d06d82cdcbc9be9656c072820b340d0152d/src/Controller/BackendController.php#L33

As a first step please check version 1.3.1.

**Comment by Defcon0** [comment]
Packagist didn't update automatically (although the webhook is in place). I updated it manually so it should be available via composer in no time.
