### ISSUE TITLE
550 Authentication required for connections on TCP port 587

### ISSUE THREAD

**Issue by V15** [heimrichhannot/contao-backend-lost-password-bundle#8]
I have a Proplem with your Extension and Contao Version 4.13.25.
If I click the Link "Forgot Password" and fill in my E-Mail address, I get the following error:

`Expected response code "250/251/252" but got code "550", with message "550 Authentication required for connections on TCP port 587"`

Is the extension not ready for 4.13?

**Comment by koertho** [comment]
Hi, this sounds like an issue with your SMTP connection, not our extension. We're already using it in many 4.13 projects.

**Comment by V15** [comment]
Thanks for your fast response.
You are right, it's a problem with the SMTP connection.
